/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author A C E R
 */
public class conform_consultent extends javax.swing.JFrame {

    private int Consultent_id;
    private String date;
    dbOperation db = new dbOperation();

    /**
     * Creates new form conform_consultent
     */
    public conform_consultent() {

        initComponents();
        LocalDate d = LocalDate.now();
        setDate(d.toString());
        jLabDate.setText(getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPatientAdmitionId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAdmissionId = new javax.swing.JTextField();
        txtDiseases = new javax.swing.JTextField();
        txtPhysical_disabilities = new javax.swing.JTextField();
        txtAllergic_Medicines = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPreviousOperationHistory = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        btnTest = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conform Consultant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Patient Admission id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 141, -1));

        txtPatientAdmitionId.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtPatientAdmitionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientAdmitionIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPatientAdmitionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 81, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("personal details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 141, -1));

        btnOK.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 60, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Admission id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 141, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Diseases");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 141, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Physical disabilities");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 141, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Allergic Medicines");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 141, -1));

        txtAdmissionId.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtAdmissionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdmissionIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtAdmissionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 178, -1));

        txtDiseases.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtDiseases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiseasesActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiseases, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 178, -1));

        txtPhysical_disabilities.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtPhysical_disabilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhysical_disabilitiesActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhysical_disabilities, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 178, -1));

        txtAllergic_Medicines.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtAllergic_Medicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergic_MedicinesActionPerformed(evt);
            }
        });
        jPanel1.add(txtAllergic_Medicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 178, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Previous Operation History");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 160, -1));

        txtPreviousOperationHistory.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtPreviousOperationHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 178, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Give");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("View test result");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 128, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Giive medicine");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 141, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 40, -1));

        jLabDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(jLabDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 90, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 599, 10));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Age");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 141, -1));

        txtAge.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtAge.setToolTipText("");
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 178, -1));

        btnTest.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnTest.setText("View Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 470));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/common.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAllergic_MedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergic_MedicinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergic_MedicinesActionPerformed

    private void txtPhysical_disabilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhysical_disabilitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhysical_disabilitiesActionPerformed

    private void txtDiseasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiseasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiseasesActionPerformed

    private void txtAdmissionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdmissionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmissionIdActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        int result = db.checkPatientId_given_table(txtPatientAdmitionId.getText(), "patient");//check patienid whether exist
        if (result == 0) {//if  method run successfully and patienid is exist result=0
            String s[] = db.get_patient_personol_details(txtPatientAdmitionId.getText());//get personal deatails to string array
            int Length = s.length;
            txtAdmissionId.setText(s[0]);
            txtAge.setText(s[1]);
            txtDiseases.setText(s[2]);
            txtPhysical_disabilities.setText(s[3]);
            txtAllergic_Medicines.setText(s[4]);
            txtPreviousOperationHistory.setText(s[5]);
        } else if (result == 1) {//if  method run successfully result=0 &patienid does not exist
            JOptionPane.showMessageDialog(this, "Patient Admition Id  doest not exist !");
        } else {//if checkPatientId_given_table  method not run successfully display massage
            JOptionPane.showMessageDialog(this, "Error occur while  execute sql Query!");
        }


    }//GEN-LAST:event_btnOKActionPerformed

    private void txtPatientAdmitionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientAdmitionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientAdmitionIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // going to display give_medicine jframe
        int result0 = db.update_patient_Table("conform_consultant_id", getConsultent_id(), Integer.parseInt(txtPatientAdmitionId.getText()));//update patient deatails
        if (result0 == 1) {
            JOptionPane.showMessageDialog(this, "Error occur while  execute update_patient_Table method !");//if error occur while update update_patient_Table display massage
        }

        int result1 = db.checkPatientId_given_table(txtPatientAdmitionId.getText(), "patient");//check patienid whether exist in patient table
        if (result1 == 0) {//if result1=0 patient id is exist 
            int result2 = db.checkPatientId_given_table(txtPatientAdmitionId.getText(), "personal_details");////check patienid whether exist in personal_details table
            if (result2 == 0) {//if result2 =0 the id is exist in the table & update personal_details table
                db.update_patient_personal_deatails(Integer.parseInt(txtAdmissionId.getText()), Integer.parseInt(txtAge.getText()), txtDiseases.getText(), txtPhysical_disabilities.getText(), txtAllergic_Medicines.getText(), txtPreviousOperationHistory.getText());
                give_medicine gm = new give_medicine();
                gm.setDate(date);
                gm.setAddmission(Integer.parseInt(txtAdmissionId.getText()));
                gm.setConsultant_id(Consultent_id);
                gm.setVisible(true);
            } else if (result2 == 1) {//if result2 =1 the id is not exist in the table & add personal_details table
                db.add_personal_deatails(Integer.parseInt(txtAdmissionId.getText()), Integer.parseInt(txtAge.getText()), txtDiseases.getText(), txtPhysical_disabilities.getText(), txtAllergic_Medicines.getText(), txtPreviousOperationHistory.getText());
                give_medicine gm = new give_medicine();
                gm.setDate(date);
                gm.setAddmission(Integer.parseInt(txtAdmissionId.getText()));
                gm.setConsultant_id(Consultent_id);
                gm.setVisible(true);
            } else if (result2 == 2) {//if result2 =0 error occur while run checkPatientId_given_table method
                JOptionPane.showMessageDialog(this, "Error occur while  execute checkPatientId_given_table method with personal_details Table!");
            }
        } else if (result1 == 1) {//result1 == 1 can not find admission_id in patient Table
            JOptionPane.showMessageDialog(this, "can't find admission_id in patient Table ");
        } else {// if result1 other one  Error occur while  execute checkPatientId_given_table method
            JOptionPane.showMessageDialog(this, "Error occur while  execute checkPatientId_given_table method with patient Table! ");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        // display testView jframe
        TestView tv = new TestView();
        tv.setComming_from("conform_consultent");
        tv.setAdmission_id(Integer.parseInt(txtAdmissionId.getText()));
        tv.setConsultentId(getComponentCount());
        tv.setDate(getDate());
        tv.update_table();
        tv.setVisible(true);
    }//GEN-LAST:event_btnTestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //  go back jframe 
        consultents c = new consultents();
        c.setVisible(true);
        c.setConsultent_id(getConsultent_id());
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conform_consultent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conform_consultent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conform_consultent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conform_consultent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conform_consultent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAdmissionId;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAllergic_Medicines;
    private javax.swing.JTextField txtDiseases;
    private javax.swing.JTextField txtPatientAdmitionId;
    private javax.swing.JTextField txtPhysical_disabilities;
    private javax.swing.JTextField txtPreviousOperationHistory;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Consultent_id
     */
    public int getConsultent_id() {
        return Consultent_id;
    }

    /**
     * @param Consultent_id the Consultent_id to set
     */
    public void setConsultent_id(int Consultent_id) {
        this.Consultent_id = Consultent_id;
    }

    /**
     * @return the date
     */
    public String getDate() {
        return date;
    }

    /**
     * @param date the date to set
     */
    public void setDate(String date) {
        this.date = date;
    }

}
