/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author A C E R
 */

public class NewUser extends javax.swing.JFrame {
    dbOperation dbo=new dbOperation();
    private int admin_id;
    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rxtNameWithInitials = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ddGeender = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFixedNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ddState = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        txtConformPassword = new javax.swing.JPasswordField();
        btmSubmit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtAddres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel8.setText("jLabel8");

        jPasswordField2.setText("jPasswordField1");

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee details ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("First Namme");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 110, -1));

        txtFirstName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 33, 150, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 35, 74, -1));

        txtLastName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 33, 146, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Name With Initials ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 71, 110, -1));

        rxtNameWithInitials.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rxtNameWithInitials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rxtNameWithInitialsActionPerformed(evt);
            }
        });
        jPanel1.add(rxtNameWithInitials, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 71, 462, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 148, 110, -1));

        txtAge.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 146, 35, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 228, 110, -1));

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 224, 462, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 103, 110, -1));

        ddGeender.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ddGeender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        ddGeender.setToolTipText("");
        ddGeender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddGeenderActionPerformed(evt);
            }
        });
        jPanel1.add(ddGeender, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 103, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Fixed No");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 264, 74, -1));

        txtMobileNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 262, 150, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Mobile No");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 264, 110, -1));

        txtFixedNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtFixedNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFixedNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFixedNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 262, 146, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("NIC");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 304, 110, -1));

        txtNic.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        jPanel1.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 300, 462, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("State");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 338, 110, 24));

        ddState.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ddState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctor", "Nurse", "Maintenance", "accountant", "admin" }));
        jPanel1.add(ddState, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 338, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 383, 110, -1));

        txtPassword.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 381, 150, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setText("Conform Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 421, -1, -1));

        txtConformPassword.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtConformPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 419, 150, -1));

        btmSubmit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btmSubmit.setText("Add");
        btmSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btmSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 403, 111, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("Addres");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 184, 110, -1));

        txtAddres.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtAddres, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 182, 462, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 457, 70, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/viewEmployee.jpg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1222, 500));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void ddGeenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddGeenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddGeenderActionPerformed

    private void txtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoActionPerformed

    private void txtFixedNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFixedNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFixedNoActionPerformed
    private void clearFields(){
    //clear the texts fields
        txtFirstName.setText("");
        txtLastName.setText("");
        rxtNameWithInitials.setText("");
        txtAge.setText("");
        txtAddres.setText("");
        txtEmail.setText("");
        txtMobileNo.setText("");
        txtFixedNo.setText("");
        txtNic.setText("");
        txtPassword.setText("");
        txtConformPassword.setText("");
        
    }
    private void btmSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSubmitActionPerformed
        // add users
        if(txtPassword.getText().equals(txtConformPassword.getText())){
        employeeDeatails em =new  employeeDeatails();
        em.setFirst_name(txtFirstName.getText());
        em.setLast_name(txtLastName.getText());
        em.setName_with_initials(rxtNameWithInitials.getText());
        em.setGender(ddGeender.getSelectedItem().toString());
        em.setAge(Integer.parseInt(txtAge.getText()));
        em.setAddress(txtAddres.getText());
        em.setEmail(txtEmail.getText());
        em.setMobile_no(Integer.parseInt(txtMobileNo.getText()));
        em.setFixed_no(Integer.parseInt(txtFixedNo.getText()));
        em.setNic(txtNic.getText());
        em.setState(ddState.getSelectedItem().toString());
        em.setPassword(txtPassword.getText());
        em.setConform_password(txtConformPassword.getText());
        boolean result=dbo.addEmployee(em);
        
        if(result){
            //display inserted is successfull
            JOptionPane.showMessageDialog(this, "successfully inserted  !!");
            if(em.getState().equals("Doctor")){
                consultant c=new consultant();
                c.setNic(em.getNic());
                //c.labele();
                c.setVisible(true);
                clearFields();//clear all text field
                        }
            else if(em.getState().equals("Nurse")){
                Nurse_ n=new Nurse_();
                n.setNic(em.getNic());
                n.setVisible(true);
                clearFields();//clear all text field
            }
            else{
                clearFields();//clear all text field
            }
        }
        else{
            //display inserted is not successfull
            JOptionPane.showMessageDialog(this, "Error occured while inserting !!");
        }
        }
        else{//when password and conform password mismatch display massage 
             JOptionPane.showMessageDialog(this, "Password mismatched   !!");
             txtPassword.setText("");//txtpassword field set empty
             txtConformPassword.setText("");//txtConformPassword field set empty
        }
        
        
        
    }//GEN-LAST:event_btmSubmitActionPerformed

    private void rxtNameWithInitialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rxtNameWithInitialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rxtNameWithInitialsActionPerformed

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // go back Admin jframe
        Admin ad =new Admin();
        ad.setAdmin_id(admin_id);
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmSubmit;
    private javax.swing.JComboBox ddGeender;
    private javax.swing.JComboBox ddState;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField rxtNameWithInitials;
    private javax.swing.JTextField txtAddres;
    private javax.swing.JTextField txtAge;
    private javax.swing.JPasswordField txtConformPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFixedNo;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtNic;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the admin_id
     */
    public int getAdmin_id() {
        return admin_id;
    }

    /**
     * @param admin_id the admin_id to set
     */
    public void setAdmin_id(int admin_id) {
        this.admin_id = admin_id;
    }
}
