/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author A C E R
 */
public class viewProfile extends javax.swing.JFrame {

    /**
     * Creates new form viewProfile
     */
    private String Emp_id;
    private String emp_state;

    public viewProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtNameWithInitials = new javax.swing.JTextField();
        ddGeender = new javax.swing.JComboBox();
        txtAge = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMobileNo = new javax.swing.JTextField();
        txtFixedNo = new javax.swing.JTextField();
        btmSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNic1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtEmpID = new javax.swing.JLabel();
        txtState = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("First Namme");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 95, 253, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Name With Initials ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 129, 253, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 162, 253, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 203, 253, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("Addres");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 239, 128, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 121, 233, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Mobile No");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 159, 233, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("NIC");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 229, 48, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("State");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 351, 242, 24));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 259, 100, -1));

        txtFirstName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 123, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 89, 74, -1));

        txtLastName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 87, 163, -1));

        txtNameWithInitials.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtNameWithInitials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameWithInitialsActionPerformed(evt);
            }
        });
        jPanel1.add(txtNameWithInitials, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 203, -1));

        ddGeender.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ddGeender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        ddGeender.setToolTipText("");
        ddGeender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddGeenderActionPerformed(evt);
            }
        });
        jPanel1.add(ddGeender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        txtAge.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 35, -1));

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 119, 163, -1));

        txtMobileNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 157, 163, -1));

        txtFixedNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtFixedNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFixedNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFixedNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 189, 163, -1));

        btmSubmit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btmSubmit.setText("Submit");
        btmSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btmSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 350, 111, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Employee Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 156, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 71, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Fixed No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 193, 74, -1));

        txtNic1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtNic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNic1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 227, 163, -1));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 189, -1));
        jPanel1.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 87, 16));
        jPanel1.add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 120, 20));

        txtPassword.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 259, 163, 16));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/viewEmployee.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameWithInitialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameWithInitialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameWithInitialsActionPerformed

    private void ddGeenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddGeenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddGeenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoActionPerformed

    private void txtFixedNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFixedNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFixedNoActionPerformed

    private void btmSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSubmitActionPerformed
        // TODO add your handling code here:
        dbOperation dbo = new dbOperation();
        employeeDeatails em = new employeeDeatails();
        em.setFirst_name(txtFirstName.getText());
        em.setLast_name(txtLastName.getText());
        em.setName_with_initials(txtNameWithInitials.getText());
        em.setGender(ddGeender.getSelectedItem().toString());
        em.setAge(Integer.parseInt(txtAge.getText()));
        em.setAddress(txtAddress.getText());
        em.setEmail(txtEmail.getText());
        em.setMobile_no(Integer.parseInt(txtMobileNo.getText()));
        em.setFixed_no(Integer.parseInt(txtFixedNo.getText()));
        em.setNic(txtPassword.getText());
        em.setState(txtState.getText());
        em.setPassword(txtPassword.getText());

        boolean result = dbo.update_Employee_details(em, txtEmpID.getText());

        if (result) {
            //say inserted is successfull
            JOptionPane.showMessageDialog(this, "successfully inserted  !!");

        } else {
            //say inserted is not successfull
            JOptionPane.showMessageDialog(this, "Error occured while inserting !!");
        }

    }//GEN-LAST:event_btmSubmitActionPerformed
    public void updateGui() {
        txtEmpID.setText(getEmp_id());
        dbOperation db = new dbOperation();
        int result = db.checkEmployeeId(getEmp_id());

        if (result == 1) {
            JOptionPane.showMessageDialog(this, " employee id not exist   !!");
        } else if (result == 2) {
            JOptionPane.showMessageDialog(this, "Error occur while execute  checkEmployeeId method  !!");
        } else if (result == 0) {
            employeeDeatails empdetail = db.view_employee_deatails(txtEmpID.getText());
            if (empdetail == null) {
                JOptionPane.showMessageDialog(this, "Error occur while execute  c method view_employee_deatails method  !!");
            } else {
                txtFirstName.setText(empdetail.getFirst_name());
                txtLastName.setText(empdetail.getLast_name());
                txtNameWithInitials.setText(empdetail.getName_with_initials());

                if (empdetail.getGender().equals("Male")) {
                    ddGeender.setSelectedIndex(0);
                } else if (empdetail.getGender().equals("Female")) {
                    ddGeender.setSelectedIndex(1);
                }
                txtAge.setText(Integer.toString(empdetail.getAge()));
                txtAddress.setText(empdetail.getAddress());
                txtEmail.setText(empdetail.getEmail());
                txtMobileNo.setText(Integer.toString(empdetail.getMobile_no()));
                txtFixedNo.setText(Integer.toString(empdetail.getFixed_no()));
                txtNic1.setText(empdetail.getNic());
                System.out.println("A" + empdetail.getState());
                txtState.setText(empdetail.getState());
                
                txtPassword.setText(empdetail.getPassword());

            }

        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNic1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmSubmit;
    private javax.swing.JComboBox ddGeender;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtEmpID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFixedNo;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtNameWithInitials;
    private javax.swing.JTextField txtNic1;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtState;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Emp_id
     */
    public String getEmp_id() {
        return Emp_id;
    }

    /**
     * @param Emp_id the Emp_id to set
     */
    public void setEmp_id(String Emp_id) {
        this.Emp_id = Emp_id;
    }

    /**
     * @return the emp_state
     */
    public String getEmp_state() {
        return emp_state;
    }

    /**
     * @param emp_state the emp_state to set
     */
    public void setEmp_state(String emp_state) {
        this.emp_state = emp_state;
    }
}
